/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppMuseumRouteImport } from './routes/_app/museum'
import { Route as AppMessagesRouteImport } from './routes/_app/messages'
import { Route as AppMarketplaceRouteImport } from './routes/_app/marketplace'
import { Route as AppHeritageRouteImport } from './routes/_app/heritage'
import { Route as AppFamilyTreeRouteImport } from './routes/_app/family-tree'
import { Route as AppExploreRouteImport } from './routes/_app/explore'
import { Route as AppDirectoryRouteImport } from './routes/_app/directory'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as AppCommunityIndexRouteImport } from './routes/_app/community.index'
import { Route as AppAdminIndexRouteImport } from './routes/_app/admin/index'
import { Route as AppProfileUsernameRouteImport } from './routes/_app/profile.$username'
import { Route as AppCommunityIdRouteImport } from './routes/_app/community.$id'
import { Route as AppAdminUsersRouteImport } from './routes/_app/admin/users'
import { Route as AppAdminSettingsRouteImport } from './routes/_app/admin/settings'
import { Route as AppAdminPaymentsRouteImport } from './routes/_app/admin/payments'
import { Route as AppAdminLogsRouteImport } from './routes/_app/admin/logs'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppMuseumRoute = AppMuseumRouteImport.update({
  id: '/museum',
  path: '/museum',
  getParentRoute: () => AppRoute,
} as any)
const AppMessagesRoute = AppMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketplaceRoute = AppMarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => AppRoute,
} as any)
const AppHeritageRoute = AppHeritageRouteImport.update({
  id: '/heritage',
  path: '/heritage',
  getParentRoute: () => AppRoute,
} as any)
const AppFamilyTreeRoute = AppFamilyTreeRouteImport.update({
  id: '/family-tree',
  path: '/family-tree',
  getParentRoute: () => AppRoute,
} as any)
const AppExploreRoute = AppExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => AppRoute,
} as any)
const AppDirectoryRoute = AppDirectoryRouteImport.update({
  id: '/directory',
  path: '/directory',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppCommunityIndexRoute = AppCommunityIndexRouteImport.update({
  id: '/community/',
  path: '/community/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppProfileUsernameRoute = AppProfileUsernameRouteImport.update({
  id: '/profile/$username',
  path: '/profile/$username',
  getParentRoute: () => AppRoute,
} as any)
const AppCommunityIdRoute = AppCommunityIdRouteImport.update({
  id: '/community/$id',
  path: '/community/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminSettingsRoute = AppAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminPaymentsRoute = AppAdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminLogsRoute = AppAdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AppAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AppAdminRouteWithChildren
  '/directory': typeof AppDirectoryRoute
  '/explore': typeof AppExploreRoute
  '/family-tree': typeof AppFamilyTreeRoute
  '/heritage': typeof AppHeritageRoute
  '/marketplace': typeof AppMarketplaceRoute
  '/messages': typeof AppMessagesRoute
  '/museum': typeof AppMuseumRoute
  '/admin/logs': typeof AppAdminLogsRoute
  '/admin/payments': typeof AppAdminPaymentsRoute
  '/admin/settings': typeof AppAdminSettingsRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/community/$id': typeof AppCommunityIdRoute
  '/profile/$username': typeof AppProfileUsernameRoute
  '/admin/': typeof AppAdminIndexRoute
  '/community/': typeof AppCommunityIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/directory': typeof AppDirectoryRoute
  '/explore': typeof AppExploreRoute
  '/family-tree': typeof AppFamilyTreeRoute
  '/heritage': typeof AppHeritageRoute
  '/marketplace': typeof AppMarketplaceRoute
  '/messages': typeof AppMessagesRoute
  '/museum': typeof AppMuseumRoute
  '/': typeof AppIndexRoute
  '/admin/logs': typeof AppAdminLogsRoute
  '/admin/payments': typeof AppAdminPaymentsRoute
  '/admin/settings': typeof AppAdminSettingsRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/community/$id': typeof AppCommunityIdRoute
  '/profile/$username': typeof AppProfileUsernameRoute
  '/admin': typeof AppAdminIndexRoute
  '/community': typeof AppCommunityIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/admin': typeof AppAdminRouteWithChildren
  '/_app/directory': typeof AppDirectoryRoute
  '/_app/explore': typeof AppExploreRoute
  '/_app/family-tree': typeof AppFamilyTreeRoute
  '/_app/heritage': typeof AppHeritageRoute
  '/_app/marketplace': typeof AppMarketplaceRoute
  '/_app/messages': typeof AppMessagesRoute
  '/_app/museum': typeof AppMuseumRoute
  '/_app/': typeof AppIndexRoute
  '/_app/admin/logs': typeof AppAdminLogsRoute
  '/_app/admin/payments': typeof AppAdminPaymentsRoute
  '/_app/admin/settings': typeof AppAdminSettingsRoute
  '/_app/admin/users': typeof AppAdminUsersRoute
  '/_app/community/$id': typeof AppCommunityIdRoute
  '/_app/profile/$username': typeof AppProfileUsernameRoute
  '/_app/admin/': typeof AppAdminIndexRoute
  '/_app/community/': typeof AppCommunityIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/directory'
    | '/explore'
    | '/family-tree'
    | '/heritage'
    | '/marketplace'
    | '/messages'
    | '/museum'
    | '/admin/logs'
    | '/admin/payments'
    | '/admin/settings'
    | '/admin/users'
    | '/community/$id'
    | '/profile/$username'
    | '/admin/'
    | '/community/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/directory'
    | '/explore'
    | '/family-tree'
    | '/heritage'
    | '/marketplace'
    | '/messages'
    | '/museum'
    | '/'
    | '/admin/logs'
    | '/admin/payments'
    | '/admin/settings'
    | '/admin/users'
    | '/community/$id'
    | '/profile/$username'
    | '/admin'
    | '/community'
  id:
    | '__root__'
    | '/_app'
    | '/auth'
    | '/_app/admin'
    | '/_app/directory'
    | '/_app/explore'
    | '/_app/family-tree'
    | '/_app/heritage'
    | '/_app/marketplace'
    | '/_app/messages'
    | '/_app/museum'
    | '/_app/'
    | '/_app/admin/logs'
    | '/_app/admin/payments'
    | '/_app/admin/settings'
    | '/_app/admin/users'
    | '/_app/community/$id'
    | '/_app/profile/$username'
    | '/_app/admin/'
    | '/_app/community/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/museum': {
      id: '/_app/museum'
      path: '/museum'
      fullPath: '/museum'
      preLoaderRoute: typeof AppMuseumRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/messages': {
      id: '/_app/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AppMessagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/marketplace': {
      id: '/_app/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof AppMarketplaceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/heritage': {
      id: '/_app/heritage'
      path: '/heritage'
      fullPath: '/heritage'
      preLoaderRoute: typeof AppHeritageRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/family-tree': {
      id: '/_app/family-tree'
      path: '/family-tree'
      fullPath: '/family-tree'
      preLoaderRoute: typeof AppFamilyTreeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/explore': {
      id: '/_app/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof AppExploreRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/directory': {
      id: '/_app/directory'
      path: '/directory'
      fullPath: '/directory'
      preLoaderRoute: typeof AppDirectoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/community/': {
      id: '/_app/community/'
      path: '/community'
      fullPath: '/community/'
      preLoaderRoute: typeof AppCommunityIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/': {
      id: '/_app/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/profile/$username': {
      id: '/_app/profile/$username'
      path: '/profile/$username'
      fullPath: '/profile/$username'
      preLoaderRoute: typeof AppProfileUsernameRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/community/$id': {
      id: '/_app/community/$id'
      path: '/community/$id'
      fullPath: '/community/$id'
      preLoaderRoute: typeof AppCommunityIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/users': {
      id: '/_app/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/settings': {
      id: '/_app/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AppAdminSettingsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/payments': {
      id: '/_app/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AppAdminPaymentsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/logs': {
      id: '/_app/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AppAdminLogsRouteImport
      parentRoute: typeof AppAdminRoute
    }
  }
}

interface AppAdminRouteChildren {
  AppAdminLogsRoute: typeof AppAdminLogsRoute
  AppAdminPaymentsRoute: typeof AppAdminPaymentsRoute
  AppAdminSettingsRoute: typeof AppAdminSettingsRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminLogsRoute: AppAdminLogsRoute,
  AppAdminPaymentsRoute: AppAdminPaymentsRoute,
  AppAdminSettingsRoute: AppAdminSettingsRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppDirectoryRoute: typeof AppDirectoryRoute
  AppExploreRoute: typeof AppExploreRoute
  AppFamilyTreeRoute: typeof AppFamilyTreeRoute
  AppHeritageRoute: typeof AppHeritageRoute
  AppMarketplaceRoute: typeof AppMarketplaceRoute
  AppMessagesRoute: typeof AppMessagesRoute
  AppMuseumRoute: typeof AppMuseumRoute
  AppIndexRoute: typeof AppIndexRoute
  AppCommunityIdRoute: typeof AppCommunityIdRoute
  AppProfileUsernameRoute: typeof AppProfileUsernameRoute
  AppCommunityIndexRoute: typeof AppCommunityIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRouteWithChildren,
  AppDirectoryRoute: AppDirectoryRoute,
  AppExploreRoute: AppExploreRoute,
  AppFamilyTreeRoute: AppFamilyTreeRoute,
  AppHeritageRoute: AppHeritageRoute,
  AppMarketplaceRoute: AppMarketplaceRoute,
  AppMessagesRoute: AppMessagesRoute,
  AppMuseumRoute: AppMuseumRoute,
  AppIndexRoute: AppIndexRoute,
  AppCommunityIdRoute: AppCommunityIdRoute,
  AppProfileUsernameRoute: AppProfileUsernameRoute,
  AppCommunityIndexRoute: AppCommunityIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
